start_urls:
  - https://jsonplaceholder.typicode.com/todos/1

allowed_domains:
  - typicode.com

extract:
  - page:
      page_type: feed
      url_patterns:
        - https://jsonplaceholder.typicode.com/todos/
      item_rules:
        userid: re{re.findall('userId":\s(\d+)', response.text)[0]}
        id: re{re.findall('id":\s(\d+)', response.text)[0]}
        title: re{re.findall('title\":\s"(.*)\"', response.text)[0]}
        completed: re{re.findall('completed":\s(.*)', response.text)[0]}
      code_file: json.py
      code: "
      for result in results: \n
          \t print(result['userid'])\n
      process(response, results, next_page_url)\n
      "